/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:cd422f56-eb33-4f4a-82a5-683417e52f5f",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_sYx99oF2B",
    "aws_user_pools_web_client_id": "n9r4pui9bdmt2bgpkk9ov0fj9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dsqe37tub5etnor7cryxivzgyy.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fwwl5ignpfcjlgfnpuo53l6f7u",
    "aws_user_files_s3_bucket": "tutorial-bucket162029-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
