/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:cd422f56-eb33-4f4a-82a5-683417e52f5f",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_sYx99oF2B",
    "aws_user_pools_web_client_id": "n9r4pui9bdmt2bgpkk9ov0fj9",
    "oauth": {}
};


export default awsmobile;
